# Generated by Django 3.1.5 on 2021-04-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210428_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='cover',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
