# Generated by Django 3.1.5 on 2021-04-30 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_music_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='cover',
        ),
    ]
